### ISSUE TITLE
插件被 Chrome 拦截了

### ISSUE THREAD

**Issue by spacewander** [seekerlee/SoundPirate#27]
报错如下：
> Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.

试了下调大图片的大小，可以绕过，不过太丑了，另外图片面积太大也会影响页面操作。似乎要想别的办法触发下载了？

**Comment by seekerlee** [comment]
好像新版没有这个问题了，我更新了声海盗2.0，测试ok，如果有问题，请重新打开。
