### ISSUE TITLE
同样的 url 不再旋转下载图标

### ISSUE THREAD

**Issue by seekerlee** [seekerlee/SoundPirate#30]
网易和虾米现在学会分片下载 mp3 省流量了，后果就是一段音乐会有无数请求，现象是下载图标疯狂旋转十分鬼畜令人害怕。1 个解决方法是记住上次的 url，如果一样就不旋转了。

**Comment by faonecze** [comment]
我再补充一下同样一首歌去打开扩展跟不打开扩展速度很不一样，而且很多时候就卡住不动了。
还有为啥打开插件后似乎不管放不放歌都会占用宽带呢？这是为什么？

**Comment by jamzhou** [comment]
不停地去下载资源，然后导致IP的流量很大。在公司环境下，使用要注意了

**Comment by junglegiant** [comment]
我也遇到这种情况，图标疯狂旋转，几分钟后我的电脑就会开始发热呼呼作响。请问记住上次的URL是怎么做到呢？

> 网易和虾米现在学会分片下载 mp3 省流量了，后果就是一段音乐会有无数请求，现象是下载图标疯狂旋转十分鬼畜令人害怕。1 个解决方法是记住上次的 url，如果一样就不旋转了。

**Comment by seekerlee** [comment]
2.0 解决了，请到 chrome web store 更新或者自己打包。
