### ISSUE TITLE
1.9.1在虾米网站上播放时，会满速写硬盘，导致系统卡死

### ISSUE THREAD

**Issue by Jamwe** [seekerlee/SoundPirate#31]
Chrome： 65.0.3325.181（64 位）
Windows：Win 10 LSTB 2016。
杀软：ESET NOD32 64位版；火绒

Chrome已关闭其它扩展，在虾米音乐网站在线播放时，每次都出现这个问题，QQ/百度没有这个问题。

**Comment by seekerlee** [comment]
2.0 解决了，请到 chrome web store 更新或者自己打包。

**Comment by Jamwe** [comment]
> 2.0 解决了，请到 chrome web store 更新或者自己打包。

非常感谢作者的付出。
